---
title: "Time series in the analysis of truck sales"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	keep_md =  FALSE
)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(ggfortify)
library(lmtest)
library(forecast)
library(stringr)
library(zoo)
library(knitr)
library(lmtest)
library(tseries)
library(nortest)
```

## Data

```{r}
data<-read.csv("Truck_sales.csv")
data_copy <- data
colnames(data_copy) <- c("YearMonth","Sales") 
kable(t(head(data_copy)))
```

```{r}
data$Year <- as.numeric(paste0('20',str_sub(data$Month.Year, start = 1 , end =2)))  
data$Month <- str_sub(data$Month.Year, start = 4, end = 6)
data$YearMonth <- paste(data$Year, data$Month, sep = "-")
```

The following dataset shows monthly truck sales data from 2003 to 2014. It includes information on the number of trucks sold in each month.

## Basic statistics

```{r}
basic_stats <- data.frame(
  Metric = c("N obs.", "Średnia", "Odch. stand.", "Min", 
             "1 kwartyl", "Mediana", "3 kwartyl", "Max"),
  Value = c(
    nrow(data),                       
    mean(data$Number_Trucks_Sold, na.rm = TRUE),  
    sd(data$Number_Trucks_Sold, na.rm = TRUE),    
    min(data$Number_Trucks_Sold, na.rm = TRUE), 
    quantile(data$Number_Trucks_Sold, 0.25, na.rm = TRUE),
    median(data$Number_Trucks_Sold, na.rm = TRUE),          
    quantile(data$Number_Trucks_Sold, 0.75, na.rm = TRUE),  
    max(data$Number_Trucks_Sold, na.rm = TRUE)              
  )
)
transposed_stats <- as.data.frame(t(basic_stats))
colnames(transposed_stats) <- basic_stats$Metric
transposed_stats <- transposed_stats[-1, ]  
kable(transposed_stats, align = "c")
```



